In [1]:
import math as matematica 

In [3]:
matematica

<module 'math' from '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload/math.cpython-313-darwin.so'>

In [4]:
import numpy as np

In [6]:
np.__version__

'2.1.3'

In [7]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr, type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr, type(arr), arr.dtype)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype=np.int8)
print(arr, type(arr), arr.dtype)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int8


In [12]:
2 ** 8

256

In [14]:
arr = np.array([1, 2, 3, 4, 5, 255], dtype=np.uint8)
print(arr, type(arr), arr.dtype)

[  1   2   3   4   5 255] <class 'numpy.ndarray'> uint8


In [16]:
2 ** 7 - 1

127

In [17]:
arr = np.array([1, 2, 3, 4, 5, 127], dtype=np.int8)
print(arr, type(arr), arr.dtype)

[  1   2   3   4   5 127] <class 'numpy.ndarray'> int8


In [19]:
arr = np.array([1, 2, 3, 4, 5, -128], dtype=np.int8)
print(arr, type(arr), arr.dtype)

[   1    2    3    4    5 -128] <class 'numpy.ndarray'> int8


In [20]:
arr = np.array([1, 2, 3, 4, 5, -128])
print(arr, type(arr), arr.dtype)

[   1    2    3    4    5 -128] <class 'numpy.ndarray'> int64


In [21]:
2 ** 63 - 1

9223372036854775807

In [23]:
len(str(2 ** 63 - 1))

19