In [1]:
import numpy as np

In [2]:
text = "23,41,5,31,51,51,523,623,51,32,31"
numere = text.split(",")
numere

['23', '41', '5', '31', '51', '51', '523', '623', '51', '32', '31']

In [3]:
text = "23,41,5,31,51,51,523,623,51,32,31"
array = np.fromstring(text, sep=",")
array

array([ 23.,  41.,   5.,  31.,  51.,  51., 523., 623.,  51.,  32.,  31.])

In [4]:
array[0], type(array[0])

(np.float64(23.0), numpy.float64)

In [6]:
text = "23,branza,5,31,51,51,523,623,51,32,31"
array = np.fromstring(text, sep=",")
array

/var/folders/93/qw471b_96px9kvlzs8__bk480000gn/T/ipykernel_12588/2310205687.py:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  array = np.fromstring(text, sep=",")


array([23.])

In [10]:
text = "23,41,5,31,51,51,523,623,51,32,31"
array = np.fromstring(text, sep=",", dtype=np.int8)
array

array([ 23,  41,   5,  31,  51,  51,  11, 111,  51,  32,  31], dtype=int8)

In [12]:
np.unique(numere, return_counts=True)

(array(['23', '31', '32', '41', '5', '51', '523', '623'], dtype='<U3'),
 array([1, 2, 1, 1, 1, 3, 1, 1]))

In [13]:
valori, frecvente = np.unique(numere, return_counts=True)


In [14]:
valori[frecvente == 1]

array(['23', '32', '41', '5', '523', '623'], dtype='<U3')

In [16]:
text = "23,41,5,5,23,31,51,51,523,623,51,32,31"
numere = np.fromstring(text, sep=",", dtype=np.int8)
valori, frecvente = np.unique(numere, return_counts=True)
valori[frecvente == 1]


array([ 11,  32,  41, 111], dtype=int8)