In [1]:
import numpy as np

In [2]:
array = np.arange(1, 10)
array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
def aduna_unu(x):
    return x + 1

In [6]:
vectorized_aduna_unu = np.vectorize(aduna_unu)

In [7]:
vectorized_aduna_unu(array)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.vectorize(lambda x:x ** 2)(array)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
array + array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
array * 2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array = array ** 2

In [16]:
array

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])