In [1]:
import random

In [2]:
random.random()

0.8431017476805127

In [3]:
random.random()

0.36941408995437075

In [4]:
random.random()

0.942909728373534

In [5]:
random.random()

0.7092342065736795

In [6]:
random.randint(1, 10)

5

In [7]:
random.randint(1, 10)

3

In [9]:
random.randint(1, 2)

2

In [10]:
import numpy as np

In [11]:
np.random.random()

0.5152299472482194

In [12]:
np.random.random()

0.25496993005580615

In [13]:
np.random.random(10)

array([0.09872353, 0.91759656, 0.35627845, 0.39483171, 0.83790185,
       0.51892827, 0.29733097, 0.03467715, 0.83983824, 0.79304985])

In [14]:
np.random.randint(0, 100)

66

In [15]:
np.random.randint(0, 100, 10)

array([52, 35, 49, 15, 85, 62, 40,  6, 59, 40])

In [ ]:
np.random.randint(0, 100, 10)

array([40, 69, 88, 34, 61, 29, 81, 78, 59,  8])

In [17]:
np.random.randint(0, 100, (3, 2))

array([[66, 97],
       [60, 17],
       [58, 18]])

In [18]:
matrice = np.random.randint(0, 100, (3, 2))
matrice

array([[12, 54],
       [73, 48],
       [11, 53]])

In [19]:
matrice[2][0]

np.int64(11)

In [20]:
matrice[-1]

array([11, 53])

In [21]:
matrice[::-1]

array([[11, 53],
       [73, 48],
       [12, 54]])

In [22]:
matrice.shape, matrice.size, matrice.ndim

((3, 2), 6, 2)

In [23]:
matrice.reshape((2,3))

array([[12, 54, 73],
       [48, 11, 53]])

In [25]:
matrice.reshape((1,6))

array([[12, 54, 73, 48, 11, 53]])

In [26]:
matrice.reshape((6,))

array([12, 54, 73, 48, 11, 53])

In [27]:
matrice.flatten()


array([12, 54, 73, 48, 11, 53])

In [28]:
matrice.T

array([[12, 73, 11],
       [54, 48, 53]])