In [3]:
import numpy as np

In [5]:
np.random.randint(10, 45, 10)

array([32, 43, 13, 28, 40, 23, 22, 28, 19, 30])

In [6]:
np.random.uniform(10, 45, 10)

array([36.3985401 , 34.32739331, 17.8682258 , 32.88466952, 31.60541544,
       43.86935023, 14.73379181, 10.31380711, 22.33527092, 12.82481524])

In [7]:
np.random.randint(10, 45, 10)

array([17, 32, 12, 21, 27, 40, 15, 35, 43, 22])

In [8]:
np.random.randint(10, 45, (5, 2))

array([[42, 21],
       [17, 20],
       [35, 31],
       [32, 11],
       [36, 15]])

In [9]:
np.random.randint(10, 45, (30,  3))

array([[40, 14, 16],
       [42, 17, 41],
       [35, 18, 26],
       [37, 21, 38],
       [19, 19, 30],
       [35, 42, 23],
       [41, 20, 13],
       [14, 39, 11],
       [36, 25, 11],
       [39, 38, 35],
       [31, 38, 26],
       [34, 30, 14],
       [18, 28, 31],
       [29, 36, 13],
       [34, 20, 15],
       [26, 22, 44],
       [36, 24, 20],
       [38, 10, 41],
       [18, 26, 20],
       [42, 44, 37],
       [12, 34, 23],
       [19, 39, 22],
       [18, 29, 22],
       [11, 23, 39],
       [26, 13, 30],
       [44, 26, 27],
       [14, 22, 37],
       [11, 22, 18],
       [42, 37, 24],
       [24, 17, 18]])

In [10]:
np.random.randint(10, 45, (3,  30))

array([[42, 19, 33, 20, 39, 25, 41, 25, 14, 37, 29, 19, 31, 12, 27, 42,
        22, 28, 17, 19, 37, 38, 31, 41, 37, 27, 13, 13, 36, 26],
       [16, 22, 22, 41, 31, 31, 29, 43, 40, 29, 39, 13, 21, 40, 37, 18,
        31, 10, 19, 38, 43, 18, 14, 21, 16, 26, 40, 19, 42, 27],
       [13, 25, 11, 14, 13, 18, 24, 22, 12, 17, 35, 21, 26, 19, 18, 43,
        24, 40, 31, 32, 35, 23, 13, 30, 16, 39, 14, 22, 35, 17]])

In [13]:
date = np.random.randint(10, 45, (30,  3))
date


array([[26, 12, 15],
       [30, 36, 23],
       [39, 10, 29],
       [21, 33, 14],
       [40, 13, 44],
       [11, 16, 30],
       [33, 19, 42],
       [23, 42, 29],
       [33, 22, 36],
       [15, 28, 20],
       [39, 16, 19],
       [21, 36, 16],
       [23, 27, 15],
       [28, 34, 30],
       [44, 13, 16],
       [21, 24, 27],
       [27, 34, 22],
       [40, 38, 23],
       [26, 14, 41],
       [20, 34, 29],
       [20, 18, 31],
       [15, 11, 33],
       [27, 24, 17],
       [19, 32, 11],
       [34, 10, 31],
       [24, 32, 38],
       [22, 29, 21],
       [26, 33, 19],
       [17, 43, 18],
       [13, 18, 42]])

In [12]:
date.mean()

np.float64(27.166666666666668)

In [15]:
len(date.mean(axis=1))

30

In [16]:
array = np.array([[0, 1],[2, 3]])
array.mean()



np.float64(1.5)

In [17]:
array = np.array([[0, 1],
                  [2, 3]])
array.mean(axis=0)

array([1., 2.])

In [18]:
array = np.array([[0, 1],
                  [2, 3]])
array.mean(axis=1)

array([0.5, 2.5])

In [20]:
date.mean(axis=0)

array([25.9       , 25.03333333, 26.03333333])

In [21]:
np.mean(date, axis=0)

array([25.9       , 25.03333333, 26.03333333])

In [22]:
medii_per_zi = date.mean(axis=1)

In [23]:
medii_per_statie = date.mean(axis=0)

In [24]:
diferentele = np.ptp(date, axis=1)

In [27]:
diferentele

array([14, 13, 29, 19, 31, 19, 23, 19, 14, 13, 23, 20, 12,  6, 31,  6, 12,
       17, 27, 14, 13, 22, 10, 21, 24, 14,  8, 14, 26, 29])

In [28]:
diferentele.max(), diferentele.argmax()

(np.int64(31), np.int64(4))