In [1]:
import numpy as np

In [3]:
vector_a = np.arange(1, 4)
vector_b = np.arange(4, 7) 
vector_a, vector_b

(array([1, 2, 3]), array([4, 5, 6]))

In [4]:
vector_a + vector_b

array([5, 7, 9])

In [5]:
vector_a * vector_b

array([ 4, 10, 18])

In [6]:
np.dot(vector_a, vector_b)

np.int64(32)

In [7]:
matrice_a = np.array([[1, 1], 
                      [1, 2], 
                      [1, 3]])
matrice_a

array([[1, 1],
       [1, 2],
       [1, 3]])

In [9]:
matrice_b = np.array([[1,1,1],
                      [1,2,3]])

In [10]:
np.dot(matrice_a, matrice_b)

array([[ 2,  3,  4],
       [ 3,  5,  7],
       [ 4,  7, 10]])