In [ ]:
!python --version

Python 3.11.13


In [ ]:
!pip install numpy

In [ ]:
!pip install matplotlib tensorflow pandas

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.18.0'

In [ ]:
scalar = tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
print(scalar.dtype, scalar.ndim, scalar.shape)

<dtype: 'int32'> 0 ()


In [ ]:
vector = tf.constant([1, 2, 3, 4])

In [ ]:
vector.numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
type(vector), type(vector.numpy())

(tensorflow.python.framework.ops.EagerTensor, numpy.ndarray)

In [ ]:
vector_a = tf.constant([1, 2, 3])
vector_b = tf.constant([[4, 5, 6], [7, 8, 9], [10, 11, 12]])

adunare = tf.add(vector_a, vector_b)
scadere = tf.subtract(vector_a, vector_b)
multiplicare = tf.multiply(vector_a, vector_b)
impartire = tf.divide(vector_a, vector_b)

In [ ]:
print(adunare, scadere, multiplicare, impartire)

tf.Tensor([5 7 9], shape=(3,), dtype=int32) tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32) tf.Tensor([ 4 10 18], shape=(3,), dtype=int32) tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [ ]:
vector_b_transpus = tf.transpose(vector_b)
vector_b_transpus, vector_b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 4,  7, 10],
        [ 5,  8, 11],
        [ 6,  9, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [ ]:
np.dot(vector_a, vector_b_transpus)

array([32, 50, 68], dtype=int32)

In [ ]:
import numpy as np

In [ ]:
array = np.array([4, 5, 6])

In [ ]:
array.reshape(-1, 1)

array([[4],
       [5],
       [6]])

In [ ]:
array = np.array([[4, 5, 6],[7, 8, 9]])
array.T

array([[4, 7],
       [5, 8],
       [6, 9]])

In [ ]:
class DenseLayer(tf.keras.layers.Layer):
  def __init__(self, n_output_nodes):
      self.n_output_nodes = n_output_nodes

  def build(self, input_shape):
    d = int(input_shape[-1])
    self.W = self.add_weight("weight", shape=[d, self.n_output_nodes ])
    self.b = self.add_weight("bias", shape=[1, self.n_output_nodes])

  def call(self, x):
    z = tf.matmul(x, self.W) + self.b
    y = tf.sigmoid(z)
    return z



In [ ]:
layer = DenseLayer(3)
layer.build([[1, 2]])


x_input = tf.constant([[1, 2.]], shape=(1, 2))
y = layer.call(x_input)

print(y)
print(y.numpy())


AttributeError: 'DenseLayer' object has no attribute '_parent_path'

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
n_output_nodes = 3

model = Sequential()
dense_layer = Dense(n_output_nodes, activation="sigmoid")
model.add(dense_layer)


In [ ]:
x_input = tf.constant([[1, 2]], shape=(1, 2))
x_input

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [ ]:
model_output = model(x_input)
model_output

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.23698764, 0.26061043, 0.7270571 ]], dtype=float32)>

In [ ]:
model_output.numpy()

array([[0.23698764, 0.26061043, 0.7270571 ]], dtype=float32)