In [2]:
import numpy as np

In [3]:
input_data = np.array([(-1, -108), (11, -96), (8, -99), (-6, -113)])
real_output_data = np.array([1, 0, 0, 1])

In [6]:
list(zip(input_data, real_output_data))

[(array([  -1, -108]), np.int64(1)),
 (array([ 11, -96]), np.int64(0)),
 (array([  8, -99]), np.int64(0)),
 (array([  -6, -113]), np.int64(1))]

In [ ]:
def mse_loss(y_real, y_prezis):
    return ((np.array(y_real) - np.array(y_prezis)) ** 2).mean()

def sigmoid(x):
    return 1/ ( 1 + np.exp(-x))

def deriv_sigmoid(x):
    fx = sigmoid(x)
    return fx * (1 - fx)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def __str__(self):
        return f"Neuronul cu greutatile {self.weights} si bias {self.bias}"
        
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)
    

class NeuralNetwork:

    def __init__(self):
        self.w1 = np.random.normal()
        self.w2 = np.random.normal()
        self.w3 = np.random.normal()
        self.w4 = np.random.normal()
        self.w5 = np.random.normal()
        self.w6 = np.random.normal()

        self.b1 = np.random.normal() 
        self.b2 = np.random.normal() 
        self.b3 = np.random.normal() 

        self.hidden1 = Neuron([self.w1, self.w2], self.b1)
        self.hidden2 = Neuron([self.w3, self.w4], self.b2)
        self.output = Neuron([self.w5, self.w6], self.b3)

    ## Folosirea modelului (DEJA ANTRENARE)
    def feedforward(self, input):
        ouput_hidden1 = self.hidden1.feedforward(input)
        ouput_hidden2 = self.hidden2.feedforward(input)

        result_output_layer = self.output.feedforward([ouput_hidden1, ouput_hidden2])

        return result_output_layer
    

    def train(self, data, true_output):
        learning_rate = 0.1 # 0.01 0.001
        EPOCH = 1000
        for i in range(EPOCH):
            for x, y_true  in zip(input_data, real_output_data):
                sum_hidden1 = self.w1 * x[0] + self.w2 * x[1] + self.b1
                h1 = sigmoid(sum_hidden1)

                sum_hidden2 = self.w3 * x[0] + self.w4 * x[1] + self.b2
                h2 = sigmoid(sum_hidden2)

                sum_output2 = self.w5 * h1 + self.w6 * h2 + self.b3
                o1 = sigmoid(sum_output2)

                y_prezis = o1

                # ((y_true - y_prezis) ** 2) / 2

                derivata_y_prezis = -2 * (y_true - y_prezis)

                derivata_w5_y_prezis = h1 * deriv_sigmoid(sum_hidden1)
                derivata_w6_y_prezis = h2 * deriv_sigmoid(sum_hidden1)
                derivata_b3_y_prezis = deriv_sigmoid(sum_hidden1)

                derivata_h1_y_prezis = self.w5 * deriv_sigmoid(sum_hidden1)
                derivata_h2_y_prezis = self.w6 * deriv_sigmoid(sum_hidden1)


                self.w1 = self.w1 - learning_rate * derivata_y_prezis * derivata_h1_y_prezis
                self.w2 = self.w2 - learning_rate * derivata_y_prezis * derivata_h2_y_prezis
                self.b1 = self.b1 - learning_rate * derivata_y_prezis * derivata_h2_y_prezis



In [9]:
my_network = NeuralNetwork()
my_network.feedforward(input_data[2])


np.float64(0.7671704616092968)

In [10]:
my_network.train(input_data, real_output_data)

In [11]:
date = {
    "Florin" : [92, 183, False],
    "Emilia" : [62, 163, True],
    "George" : [77, 178, False],
    "Iulia" : [58, 156, True]
}


In [13]:
emilia = np.array(date["Emilia"][:2])
emilia

array([ 62, 163])

In [14]:
my_network.feedforward(emilia)

np.float64(0.872316776240199)