In [1]:
import numpy as np

In [3]:
colectie = [10, 20, 30, 300.441]
arr = np.array(colectie)
print(arr, type(arr), arr.dtype)

[ 10.     20.     30.    300.441] <class 'numpy.ndarray'> float64


In [4]:
colectie = [10, 20, 30, 300.441, "hello"]
arr = np.array(colectie)
print(arr, type(arr), arr.dtype)

['10' '20' '30' '300.441' 'hello'] <class 'numpy.ndarray'> <U32


In [5]:
colectie = [10, 20, 30, 300.441, "hello", ["hello", "hello"]]
arr = np.array(colectie)
print(arr, type(arr), arr.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [7]:
colectie = [["hello", 30, 30,  "hello"], [10, 20, 300.441, "hello", ]]
arr = np.array(colectie)
print(arr, type(arr), arr.dtype)

[['hello' '30' '30' 'hello']
 ['10' '20' '300.441' 'hello']] <class 'numpy.ndarray'> <U32


In [10]:
colectie = [["hello", 30, 30,  "hello"], [10, 20, 300.441, "hello", ]]
arr = np.array(colectie)
print(arr, type(arr), arr.dtype)
print("Shape:", arr.shape)

[['hello' '30' '30' 'hello']
 ['10' '20' '300.441' 'hello']] <class 'numpy.ndarray'> <U32
Shape: (2, 4)


In [13]:

array = np.zeros(5)
print(array, array.dtype, array.shape)



[0. 0. 0. 0. 0.] float64 (5,)


In [14]:

array = np.ones(5)
print(array, array.dtype, array.shape)

[1. 1. 1. 1. 1.] float64 (5,)


In [15]:
array = np.ones(3)
print(array, array.dtype, array.shape)

[1. 1. 1.] float64 (3,)


In [16]:
array = np.full(5, 22)
print(array, array.dtype, array.shape)

[22 22 22 22 22] int64 (5,)


In [17]:
array = np.full(shape=5, fill_value=22)
print(array, array.dtype, array.shape)

[22 22 22 22 22] int64 (5,)


In [ ]:


array = np.array(range(10))
print(array, array.dtype, array.shape)


[0 1 2 3 4 5 6 7 8 9] int64 (10,)


In [19]:

array = np.arange(10)
print(array, array.dtype, array.shape)

[0 1 2 3 4 5 6 7 8 9] int64 (10,)


In [20]:

array = np.arange(3, 12)
print(array, array.dtype, array.shape)

[ 3  4  5  6  7  8  9 10 11] int64 (9,)


In [21]:
array = np.arange(3, 12, 2)
print(array, array.dtype, array.shape)

[ 3  5  7  9 11] int64 (5,)
