In [1]:
from time import sleep

In [2]:

print("Ceva")
sleep(5)
print("Altceva")


Ceva
Altceva


In [3]:
from numpy import arange

In [5]:
x = arange(10)
print(x, type(x))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [6]:
x = range(10)
print(x, type(x))

range(0, 10) <class 'range'>


In [7]:
y = arange(1, 10)
print(y, len(y))

[1 2 3 4 5 6 7 8 9] 9


In [9]:
y = range(1, 10)
print(list(y), len(y))

[1, 2, 3, 4, 5, 6, 7, 8, 9] 9


In [10]:
y = arange(1, 10).reshape((3, 3))
print(y, len(y))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 3


In [11]:
y[1][2]

np.int64(6)

In [12]:
print(y[1][2])

6
