In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array = np.arange(1, 10)
len(array)

9

In [5]:
array.size

9

In [8]:
max(array), min(array)

(np.int64(9), np.int64(1))

In [9]:
array.max(), array.min()

(np.int64(9), np.int64(1))

In [10]:
sum(array)/len(array)

np.float64(5.0)

In [11]:
array.sum() / array.size

np.float64(5.0)

In [12]:
array.mean()

np.float64(5.0)

In [13]:
array = np.array([])
array.mean()

/var/folders/93/qw471b_96px9kvlzs8__bk480000gn/T/ipykernel_8020/279862279.py:2: RuntimeWarning: Mean of empty slice.
  array.mean()
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/numpy/_core/_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


np.float64(nan)

In [14]:
array = np.array([100, 300, 200, 700, -399, 120, 320, 310, 400, -399, -320])
array

array([ 100,  300,  200,  700, -399,  120,  320,  310,  400, -399, -320])

In [15]:
array > 0

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
       False, False])

In [16]:
array[array > 0]

array([100, 300, 200, 700, 120, 320, 310, 400])

In [18]:
lista = [100, 300, 200, 700, -399, 120, 320, 310, 400, -399, -320]
array = np.array(lista)
array > 0 

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
       False, False])

In [21]:
array[0], array[-1], array[-2]

(np.int64(100), np.int64(-320), np.int64(-399))

In [ ]:
lista = [100, 300, 200, 700, -399, 120, 320, 310, 400, -399, -320]
array = np.array(lista)


conditie_1 = array > 0
conditie_2 = array < 400

# conditie SI
array[ conditie_1 & conditie_2 ]



array([100, 300, 200, 120, 320, 310])

In [25]:
lista = [100, 300, 200, 700, -399, 120, 320, 310, 400, -399, -320]
array = np.array(lista)


conditie_1 = array < 0
conditie_2 = array > 400

# conditie SAU
array[ conditie_1 | conditie_2 ]

array([ 700, -399, -399, -320])

In [27]:
lista = [100, 300, 200, 700, -399, 120, 320, 310, 400, -399, -320]
array = np.array(lista)

array.max(), array.argmax()

(np.int64(700), np.int64(3))