In [2]:

ani = [1990, 1980, 2000]
etaj = [2, 3, 1]
mp = [50, 60, 80]
pret = [70_000, 80_000, 120_000]


list(zip(ani, etaj, mp))




[(1990, 2, 50), (1980, 3, 60), (2000, 1, 80)]

In [3]:
[(0, 2, 50), (-10, 3, 60), (10, 1, 80)]

[(0, 2, 50), (-10, 3, 60), (10, 1, 80)]

In [6]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [5]:
scaler = StandardScaler()

In [8]:

ani = [1990, 1980, 2000]
etaj = [2, 3, 1]
mp = [50, 60, 80]
pret = [70_000, 80_000, 120_000]


date_de_scalat = np.array(list(zip(ani, etaj, mp)))
date_de_scalat

array([[1990,    2,   50],
       [1980,    3,   60],
       [2000,    1,   80]])

In [10]:
scaler.fit_transform(date_de_scalat)

array([[ 0.        ,  0.        , -1.06904497],
       [-1.22474487,  1.22474487, -0.26726124],
       [ 1.22474487, -1.22474487,  1.33630621]])

In [12]:
scaler.fit_transform(np.array([2023, 3, 90000]).reshape(-1, 1))

array([[-0.68289791],
       [-0.73104246],
       [ 1.41394037]])

In [ ]:
[2023, 3, 90000]