In [1]:
import numpy as np

In [2]:
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
lista[2][1]

8

In [4]:
array = np.array(lista)

In [7]:
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
array[2][1]

np.int64(8)

In [6]:
array[2, 1]

np.int64(8)

In [8]:
lista[2, 1]

TypeError: list indices must be integers or slices, not tuple